In [1]:
import numpy

In [2]:
x=numpy.array([22,3,34,45])

In [3]:
x

array([22,  3, 34, 45])

In [4]:
print(x)

[22  3 34 45]


In [5]:
import numpy as np

In [6]:
y=np.array([22,3,34,44,78,9,78,90,45])

In [7]:
print(y)

[22  3 34 44 78  9 78 90 45]


In [8]:
print(np.__version__)

1.21.5


In [10]:
z=np.array([45,77,8,89,108,34])
print(z)

[ 45  77   8  89 108  34]


In [13]:
x1=np.array([[30,56,45,45],[45,12,56,76]])
print(x1)

[[30 56 45 45]
 [45 12 56 76]]


In [14]:
print(x1)

[[30 56 45 45]
 [45 12 56 76]]


In [15]:
y1=np.array([[30,56,45,45],[45,12,56,76],[77,8,108,34]])

In [16]:
print(y1)

[[ 30  56  45  45]
 [ 45  12  56  76]
 [ 77   8 108  34]]


In [17]:
print(y1.ndim)

2


In [19]:
print(x1[0,1])

56


In [21]:
print(x1[0,2])

45
